### ISSUE TITLE
Code License?

### ISSUE THREAD

**Issue by ghost** [DickvdBrink/TypeScriptSyntaxVisualizer#1]
I would like to use some code from this in my Apache-licensed project.
Would you be willing to grant a compatible license for such use?

Thanks for your time!

**Comment by DickvdBrink** [comment]
I don't know a lot about licensing and stuff. Still need to read into that but you are allowed to use and copy anything from it ;) I really don't mind  :)

**Comment by DickvdBrink** [comment]
You don't even have to link to the code or stuff, just copy it and everything is fine ;)

**Comment by ghost** [comment]
Thanks so much! We're using part of your code to build an open source IDE!
